### ISSUE TITLE
```java.net.ConnectException: Connection timed out: connect```; client

### ISSUE THREAD

**Issue by JedJY** [JedJY/ruby#2]
Following exception occurs when Raspberry Pi disconnects (or bad connection) and client attempts to send text:
```
java.net.ConnectException: Connection timed out: connect
 at java.net.DualStackPlainSocketImpl.connect0(Native Method)
 at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
 at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
 at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
 at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
 at java.net.PlainSocketImpl.connect(Unknown Source)
 at java.net.SocksSocketImpl.connect(Unknown Source)
 at java.net.Socket.connect(Unknown Source)
 at java.net.Socket.connect(Unknown Source)
 at java.net.Socket.<init>(Unknown Source)
 at java.net.Socket.<init>(Unknown Source)
 at net21.ex212clientbw.run(ex212clientbw.java:30)
 at net21.ex212clientbw.main(ex212clientbw.java:70)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
 at java.lang.reflect.M
```

**Comment by JedJY** [comment]
added ConnectException catch clause to client

**Comment by JedJY** [comment]
Only occurs upon localhost connection due to the Voice Synthesizer being unavailable/inaccesible by the serverside
